// export 'bag_page.dart';
export 'search_page.dart';
export 'base_page.dart';
export 'about_app_page.dart';
export 'dashboard_page.dart';
// export 'detail_category_task_page.dart';
// export 'on_board_page.dart';
// export 'on_going_complete_page.dart';
export 'profile_page.dart';
export 'splash_page.dart';
export 'client_list.dart';
